name: CI-CD with AWS CodeBuild

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Trigger AWS CodeBuild 2v
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ch1e3
        # Existing build steps (replace with your actual steps)

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Reference the secret
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  # Reference the secret

      - name: Build and tag Docker image
        run: |
          docker build -t balusubhanuprakash/e4t1:test1 .  # Replace placeholders

      - name: Push Docker image to registry
        run: |
          docker push balusubhanuprakash/e4t1:test1  # Replace placeholders
