name: CI-CD with AWS CodeBuild and Load Testing

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Trigger AWS CodeBuild 2v
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ch1e3
        # Existing build steps (replace with your actual steps)

      - name: Install Locust dependencies
        run: |
          pip install -r requirements.txt

      - name: Run load test (staging branch only)
        if: github.ref == 'refs/heads/staging'  # Run only on staging branch pushes
        steps:
          - name: Run Locust test
            run: |
              locust -f locustfile.py -n 10 -H http://localhost:8000/ # Run test with 10 users

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag Docker image (Optional - staging)
        if: github.ref == 'refs/heads/staging'  # Build staging image only on staging branch pushes
        run: |
          docker build -t balusubhanuprakash/e4t1:staging .  # Replace with desired staging image name

      - name: Push Docker image to registry (Optional - staging)
        if: github.ref == 'refs/heads/staging'  # Push staging image only on staging branch pushes
        run: |
          docker push balusubhanuprakash/e4t1:staging  # Replace with desired staging image name
